name: myenv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12.2
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - torchtext
  - numpy
  - cffi
  - pip:
    - pysoundfile
    - wandb